my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story5.urls'))
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('delete/<str:pk>', views.deleteItem, name='delete'),
    path('detail/<str:pk>', views.detail, name='detail')
]

story5/models.py
from django.db import models

# Create your models here.


class Course(models.Model):
    TERM_CHOICES = [
    ('Ganjil', 'Ganjil'),
    ('Genap', 'Genap')
    ]
    YEAR_CHOICES = [
    ('2019/2020', '2019/2020'),
    ('2020/2021', '2020/2021'),
    ('2021/2022', '2021/2022'),
    ('2022/2023', '2022/2023')
    ]
    name = models.CharField(max_length=55)
    teacher = models.CharField(max_length=101)
    sks = models.PositiveIntegerField()
    term = models.CharField(
        max_length=7, 
        choices= TERM_CHOICES,
        default= 'Ganjil')
    year = models.CharField(
        max_length=9,
        choices= YEAR_CHOICES,
        default='2019/2020'
    )
    room = models.CharField(max_length=20)
    desc = models.CharField(max_length=300)

    def __str__(self):
        return self.name

class Assignment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date = models.DateTimeField()
    name = models.CharField(max_length=101)
    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.name
    

story5/forms.py
from django import forms
from .models import Course

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'teacher', 'sks', 'term', 'year', 'room', 'desc']
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'form-control'}),
            'teacher' : forms.TextInput(attrs={'class': 'form-control'}),
            'sks' : forms.NumberInput(attrs={'class': 'form-control'}),
            'term' : forms.Select(attrs={'class': 'form-control'}),
            'year' : forms.Select(attrs={'class': 'form-control'}),
            'room' : forms.TextInput(attrs={'class': 'form-control'}),
            'desc' : forms.TextInput(attrs={'class': 'form-control'}),
        }

story5/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Course, Assignment
from .forms import CourseForm
from datetime import datetime

# Create your views here.

def index(request):
    courses = Course.objects.all()
    context = {'courses': courses}
    return render(request, 'story5/index.html', context)

def add(request):
    form = CourseForm()
    if request.method == "POST":
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, (f"Matkul {request.POST['name']} telah ditambahkan!"))
            return redirect('story5:add')
        else:
            messages.warning(request, ("Data yang Anda masukkan tidak sesuai kriteria. Harap coba lagi!"))
            return redirect('story5:add')
    context = {'form' : form}
    return render(request, 'story5/add.html', context)

def deleteItem(request, pk):
    course = Course.objects.get(id=pk)
    course.delete()
    messages.success(request, (f"Mata Kuliah {course} telah dihapus"))
    return redirect('story5:index')

def detail(request, pk):
    course = Course.objects.get(id=pk)
    assignment = Assignment.objects.filter(course = course)
    today = datetime.now().timestamp()
    passed = []
    nearDeadline = []
    farDeadline = []
    for item in assignment:
        if item.date.timestamp() < today:
            passed.append(item)
        elif item.date.timestamp() < today + 86400:
            nearDeadline.append(item)
        else:
            farDeadline.append(item)
    context = {
        'course': course, 
        'passed' : passed,
        'nearDeadline': nearDeadline,
        'farDeadline': farDeadline
        }
    return render(request, 'story5/detail.html', context)

story5/templates/story5/add.html
{% extends 'story5/base.html' %} {% block content %} {% include 'story5/navbar.html' %}
<div class="container">
    {% if messages %} {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
    </div>
    {% endfor %} {% endif %}
    <form class="mt-5" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-5">
                <label>Nama Matkul</label> {{ form.name }}
            </div>
            <div class="form-group col-md-5">
                <label for="semester">Semester</label> {{ form.term }}
            </div>
            <div class="form-group col-md-2">
                <label for="sks">Jumlah SKS</label> {{ form.sks }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-5">
                <label for="dosen">Dosen Pengampu</label> {{ form.teacher }}
            </div>
            <div class="form-group col-md-5">
                <label for="tahunAjar">Tahun Ajar</label> {{ form.year }}
            </div>
            <div class="form-group col-md-2">
                <label for="ruang">No. Ruang</label> {{ form.room }}
            </div>
        </div>
        <div class="form-group">
            <label for="deskripsi">Deskripsi</label> {{ form.desc }}
        </div>
        <button type="submit" class="btn btn-dark">Tambahkan</button>
    </form>
</div>
{% endblock content %}

story5/templates/story5/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>MatkulKU</title>
</head>

<body>
    {% block content%} {% endblock content%}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

story5/templates/story5/detail.html
{% extends 'story5/base.html' %} {% block content %} {% include 'story5/navbar.html' %}
<div class="container my-4">
    <div class="jumbotron">
        <h1 class="display-4">{{ course.name }}</h1>
        <p class="lead">{{ course.term }} {{ course.year }}</p>
        <p>{{ course.desc }}</p>
        <hr class="my-4">
        <div class="row">
            <h4 class="col-10 col-md-auto">No. Ruang : <span class="badge badge-dark">{{ course.room }}</span></h4>
            <h4 class="col-10 col-md-auto">Nama Dosen : <span class="badge badge-dark">{{ course.teacher }}</span></h4>
            <h4 class="col-10 col-md-auto">Jumlah SKS : <span class="badge badge-dark">{{ course.sks }} SKS</span></h4>
        </div>
        <ul class="list-group col-auto col-md-6">
            {% for item in nearDeadline %}
            <li class="list-group-item list-group-item-danger">
                <h5>{{ item.name }}</h5>
                <h6 class="text-secondary">{{ item.date }}</h6>
            </li>
            {% endfor %} {% for item in farDeadline %}
            <li class="list-group-item list-group-item-success">
                <h5>{{ item.name }}</h5>
                <h6 class="text-secondary">{{ item.date }}</h6>
            </li>
            {% endfor %} {% for item in passed %}
            <li class="list-group-item list-group-item-dark">
                <h5>{{ item.name }}</h5>
                <h6 class="text-secondary">{{ item.date }}</h6>
            </li>
            {% endfor %}
        </ul>
        <a class="btn btn-outline-dark mt-4" href="{% url 'story5:index' %}" role="button">BACK</a>
    </div>
</div>
{% endblock content %}

story5/templates/story5/index.html
{% extends 'story5/base.html' %} {% block content %} {% include 'story5/navbar.html' %}
<div class="container my-4">
    {% if messages %} {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show mt-4" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
    </div>
    {% endfor %} {% endif %} {% for course in courses %}
    <div class="card mt-3">
        <div class="card-body d-flex justify-content-between flex-column flex-md-row bg-dark rounded " style="background-color: #141414;">
            <div>
                <a href=" {% url 'story5:detail' course.id %} ">
                    <h5 class="card-title" style="color: #EAE41E;">{{ course.name }}</h5>
                </a>
                <h6 class="card-subtitle mb-2 text-muted ">{{ course.term }} {{ course.year }}</h6>
            </div>
            <a href="{% url 'story5:delete' course.id %} " class="card-link text-danger mt-3 mt-md-0 mr-md-4 align-self-center ">Hapus</a>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock content %}

story5/templates/story5/navbar.html
<nav class="navbar navbar-light navbar-expand-lg" style="background: linear-gradient(to right, #141414 27%, #EAE41E 0%);">
    <div class="container">
        <a class="navbar-brand font-weight-bold" style="color: #EAE41E; font-family: 'Poppins', sans-serif;" href="{% url 'story5:index' %}">MatkulKU</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link font-weight-bold text-white" href="{% url 'story5:index' %}">Dinding <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold text-white" href="{% url 'story5:add' %}">Tambahkan</a>
                </li>


            </ul>
        </div>
    </div>
</nav>